#!/usr/bin/python

import tweepy
import sys
import json
import os

# use certifi for CA certificates
import certifi

from textwrap import TextWrapper
from datetime import datetime
from elasticsearch import Elasticsearch
 
 
consumer_key=os.getenv('TWITTER_CONSUMER_KEY')
consumer_secret=os.getenv('TWITTER_CONSUMER_SECRET')
 
access_token=os.getenv('TWITTER_ACCESS_TOKEN')
 
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
 
#es = Elasticsearch()
# use certifi for CA certificates
import certifi

print "starting twit\n"

es = Elasticsearch(
    ['b648c823340792c78282600213c8eefd.us-east-1.aws.found.io'],
    http_auth=('readwrite', 'dkwdlg355ah7'),
    port=9243,
    use_ssl=True,
    verify_certs=True,
    ca_certs=certifi.where(),
)
 
class StreamListener(tweepy.StreamListener):
    status_wrapper = TextWrapper(width=60, initial_indent='    ', subsequent_indent='    ')
 
    def on_status(self, status):
        try:
            #print 'n%s %s' % (status.author.screen_name, status.created_at)
 
            json_data = status._json
            print json_data['text']
            print "got one" 
            es.create(index="idx_twp",
                      doc_type="twitter_twp",
                      body=json_data
                     )
 
        except Exception, e:
            print e
            pass
 
streamer = tweepy.Stream(auth=auth, listener=StreamListener(), timeout=3000000000 )
 
#Fill with your own Keywords bellow
terms = ['elasticsearch','elasticon', 'The Elasticsearch User Conference', 'Elastic{ON}16']
 
streamer.filter(None,terms)
#streamer.userstream(None)

